
        <p>
        <Div id="0" style="position:relative;                      width:100%; height:50px; z-index:0; background-image: url(../../WVDF_CAC_8/Images/fond.gif); background-repeat: Repeat-x; "></Div>
        <Div id="2" style="position:absolute; top:15px; left:80px;                           z-index:1;"><Span Class="Titulo_13"><%=oPAG309_01.DDValue("Csag309.Literal_50")%></Span></Div>
        <Div id="3" style="position:absolute; top:30px; left:80px;                           z-index:1;"><Span Class="Titulo_13"><%=oPAG309_01.DDValue("Csag309.Literal_01")%></Span></Div>
