<div style="position:relative; width:95%; height:34px;"><img src="Images/BackGround/Azul_Top.gif" width="100%" height="34px"/></div>
<div style="position:relative; width:95%; height:65%;"><img src="Images/BackGround/Azul_1_03.gif" width="100%" height="100%"/>
	<div style="position:absolute; top:5px; left:13px; height:100%">
		<div style="text-align:center; position:relative; top:-3px; color:#FFFFFF; font-family:Arial, Helvetica, sans-serif; font-weight:bolder; font-size:14px;"><%=oPAG309_01.DDValue("Csag309.Literal_01")%></div>
		<div id="CabecalhoAba" style="position:relative; width:97%;"></div>
		<div id="AbaDinamica" style="position:relative; top:3px; background-color: #F9F9F9;  width:96%; height:80%; ">
