<%
  aIC_16_ACTIONS     =oPAG800_01.Call ("Get_fPAG800_01_Icones_16_actions")
  aIC_16_APPS        =oPAG800_01.Call ("Get_fPAG800_01_Icones_16_apps")
  aIC_16_DEVICES     =oPAG800_01.Call ("Get_fPAG800_01_Icones_16_devices")
  aIC_16_FILESYSTEMS =oPAG800_01.Call ("Get_fPAG800_01_Icones_16_filesystems")
  aIC_16_MIMETYPES   =oPAG800_01.Call ("Get_fPAG800_01_Icones_16_mimetypes")

  aIC_22_ACTIONS     =oPAG800_01.Call ("Get_fPAG800_01_Icones_22_actions")
  aIC_22_APPS        =oPAG800_01.Call ("Get_fPAG800_01_Icones_22_apps")
  aIC_22_DEVICES     =oPAG800_01.Call ("Get_fPAG800_01_Icones_22_devices")
  aIC_22_FILESYSTEMS =oPAG800_01.Call ("Get_fPAG800_01_Icones_22_filesystems")
  aIC_22_MIMETYPES   =oPAG800_01.Call ("Get_fPAG800_01_Icones_22_mimetypes")
%>

