		</div>
		<script language="javascript" type="text/javascript" src="js/abadinamica.js"></script>
	</div>
</div>

<div style="position:relative; top:-4px; width:95%; height:40px;"><img src="Images/BackGround/Azul_1_03.gif" width="100%" height="100%"/>
	<div style="position:absolute; left:0px; top:0px; width:100%; height:100% ">
		<div class="botoes" align="center" style="position:relative; width:100%; ">
			<img src="Images/PadraoNovoBotoes/32x32/actions/filesave.gif"/>
			<img src="Images/PadraoNovoBotoes/32x32/filesystems/trashcan_full.gif"/>
			<img src="Images/PadraoNovoBotoes/32x32/actions/cancel.gif"/>
			<img src="Images/PadraoNovoBotoes/32x32/apps/xmag.gif" onClick="exibePopup('xmagpag30001')" id="xmagpag30001" style="cursor:pointer" titulo="Consulta de Usuarios" pagina="PCHV800_01.asp" />
			<img src="Images/PadraoNovoBotoes/32x32/apps/klpq.gif"/>
		</div>
	</div>
</div>
<div style="position:relative; top:-8px; width:95%; height:44px; vertical-align:top;"><img src="Images/BackGround/Azul_Botton.gif" width="100%" height="44px"/></div>
