<div class="row">
	<div class="col-sm-offset-0" style="text-align: right;">
		<hr />
		<button type="Submit" name="Novo"  id="Novo"  value="Novo"   class="btn btn-primary"><i class="fa fa-plus"></i>&nbsp;<%=oPAG312_01.DDValue("Csag312.Limpar")%></button>
		<button type="Submit" name="Clear" id="Clear" value="Reload" class="btn btn-warning"><i class="fa fa-refresh"></i>&nbsp;<%=oPAG312_01.DDValue("Csag312.Prompt")%></button>
		<hr />
	</div>
</div>