<% 
	dim version
	version = date()+time()
%>
    <title>
        CROSS HOMOLOG
    </title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta http-equiv="Content-Type" Content="text/html;charset=ISO-8859-1">
    <!--<meta http-equiv="Cache-control" content="No-Store">
<meta http-equiv="expires" content="-1">-->
    <meta name="GENERATOR" Content="Visual DataFlex Studio">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta charset="ISO-8859-1">
    <link rel="shortcut icon" type="image/x-icon" href="/wvdf_bib/images/icons/rosa-dos-ventos.ico">
    <link href="/wvdf_bib/BIB/ThirdFiles/css/bootstrap.min-3.3.7.css" rel="stylesheet" />
    <link rel="stylesheet" href="/wvdf_bib/BIB/ThirdFiles/css/dataTables.bootstrap.min-1.10.12.css">
    <!--<link rel="stylesheet" href="/wvdf_bib/BIB/ThirdFiles/css/angular-datatables.min-0.5.5.css">-->
    <link rel="stylesheet" href="/wvdf_bib/BIB/Estilos/Bibliotecas/buttons.dataTables.min.css">
    <link rel="stylesheet" href="/wvdf_bib/BIB/Estilos/Bibliotecas/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="/wvdf_bib/BIB/Estilos/Bibliotecas/buttons.bootstrap.min.css">
    <link rel="stylesheet" href="/wvdf_bib/BIB/Estilos/Bibliotecas/ng-tags-input.min.css">
    <link rel="stylesheet" href="/wvdf_bib/BIB/Estilos/Bibliotecas/ng-tags-input.bootstrap.min.css">
    <link href="/wvdf_bib/BIB/Estilos/Bibliotecas/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="/wvdf_bib/BIB/Estilos/Bibliotecas/toaster.min.css">
    <!--<link rel="stylesheet" href="https://raw.githubusercontent.com/angular-ui/bootstrap/gh-pages/ui-bootstrap-2.2.0-csp.css">-->
    <link href="/wvdf_bib/BIB/Estilos/Bibliotecas/jquery-ui-1.12.1/jquery-ui.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="/wvdf_bib/BIB/ThirdFiles/css/alertifyjs-alertify.min-1.8.0.css">
    <link rel="stylesheet" href="/wvdf_bib/BIB/ThirdFiles/css/alertifyjs-bootstrap.min-1.8.0.css">
    <link rel="stylesheet" href="/wvdf_bib/BIB/Estilos/Bibliotecas/jquery.datetimepicker.css">
    <link href="/wvdf_bib/BIB/Estilos/Bibliotecas/smart-table.css" rel="stylesheet">
    <link href="/wvdf_bib/BIB/Estilos/Bibliotecas/diretivas.css?<%response.write(version)%>" rel="stylesheet">
    <link href="/wvdf_bib/BIB/Estilos/Bibliotecas/ng-alertify.css" rel="stylesheet">
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/2.2.4/jquery.min.js"></script>

    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/angular.min.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/moment.min.js"></script>
    
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/jquery.datetimepicker.full.min.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/jquery.dataTables.min.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/bootstrap.min.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/dataTables.bootstrap.min.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/dataTables.buttons.min.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/buttons.bootstrap.min.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/jszip.min.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/pdfmake.min.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/vfs_fonts.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/buttons.colVis.min.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/buttons.flash.min.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/buttons.html5.min.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/buttons.print.min.js"></script>
    <!--<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/jquery.datetimepicker.min.js"></script>-->
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/jquery.datetimepicker.js?<%response.write(version)%>"></script>
    <script src="/wvdf_bib/BIB/Estilos/Bibliotecas/jquery-ui-1.12.1/jquery-ui.min.js" type="text/javascript"></script>
    <script src="/wvdf_bib/BIB/Estilos/Bibliotecas/jquery-ui-1.12.1/datepicker-pt-BR.js" type="text/javascript"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/angular-animate.min.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/angular-touch.min.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/angular-sanitize.min.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/smart-table.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/ui-select-infinity.js"></script>

    <!--<script src="https://rawgit.com/Eonasdan/bootstrap-datetimepicker/master/src/js/bootstrap-datetimepicker.js"></script> -->
 <!--<script src="https://rawgit.com/atais/angular-eonasdan-datetimepicker/master/dist/angular-eonasdan-datetimepicker.js"></script> -->
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/diretivas.js?<%response.write(version)%>"></script>
    <!--<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-route.js"></script>-->
    <!--<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-resource.js"></script>-->
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/angular-messages.js"></script>
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/ng-tags-input/3.1.1/ng-tags-input.js"></script> -->
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/ng-tags-input.min.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/toaster.min.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/jquery.maskedinput.js"></script>
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/2.2.0/ui-bootstrap.min.js"></script>-->
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/ui-bootstrap-tpls.min.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/angular-datatables.min.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/angular-datatables.buttons.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/alertify.min.js"></script>
    <!--Bibliotecas de SOAP-->
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/soapclient.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/angular.soap.js"></script>
    <!--Bibliotecas de Dominios-->
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/ws-dominios.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/ws-dominios-directivas.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/funcGetVariavelURL.js" type="text/javascript"></script>
    <script src="/wvdf_bib/BIB/Scripts/funcUniqueArraybyId.js" type="text/javascript"></script>
    <script src="/wvdf_bib/BIB/Scripts/funcRedimensionarIframe.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/ng-alertify.js"></script>

    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/pt-br.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/angular-locale_pt-br.js"></script>
    
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/fingerprint2.min.js"></script>
    <script src="/wvdf_bib/BIB/Scripts/fhooks.js"></script>
    <!--
<link  rel="stylesheet" href="https://rawgit.com/Eonasdan/bootstrap-datetimepicker/master/build/css/bootstrap-datetimepicker.min.css"/> 
<link  rel="stylesheet" href="https://rawgit.com/Eonasdan/bootstrap-datetimepicker/master/build/css/bootstrap-datetimepicker-standalone.css"/> 
-->
    <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/jquery.datetimepicker.full.min.js"></script>
    <% if aPrograma <> "" then %>
        <script src="/wvdf_bib/BIB/Scripts/Paginas/<%= aPrograma %>.js?<%response.write(version)%>"></script>
        <% end if %>