<% 
	dim version
	version = date()+time()
%>

<title>CROSS HOMOLOG</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1">
<meta http-equiv="Cache-control" content="No-Store">
<meta http-equiv="expires" content="-1">
<meta name="GENERATOR" content="Visual DataFlex Studio">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<meta charset="ISO-8859-1">

<link rel="shortcut icon" type="image/x-icon" href="/wvdf_bib/images/icons/rosa-dos-ventos.ico">

<link rel="stylesheet" href="/wvdf_bib/BIB/Template/css/bootstrap.min.css?<%response.write(version)%>">
<!-- <link rel="stylesheet" href="/wvdf_bib/BIB/Template/css/font-awesome.css?<%response.write(version)%>">-->
<link rel="stylesheet" href="/wvdf_bib/BIB/Template/css/ace-fonts.css?<%response.write(version)%>">
<link rel="stylesheet" href="/wvdf_bib/BIB/Template/css/ace.css?<%response.write(version)%>" class="ace-main-stylesheet" id="main-ace-style">
<link rel="stylesheet" href="/wvdf_bib/BIB/Template/css/ace-skins.css?<%response.write(version)%>">
<link rel="stylesheet" href="/wvdf_bib/BIB/Estilos/Bibliotecas/jquery.alertify.css?<%response.write(version)%>">
<link rel="stylesheet" href="/wvdf_bib/BIB/Estilos/Bibliotecas/jquery.alertify.theme.css?<%response.write(version)%>">
<link rel="stylesheet" href="/wvdf_bib/BIB/Estilos/Bibliotecas/Fancybox/jquery.fancybox.css?v=2.1.5">
<link rel="stylesheet" href="/wvdf_bib/BIB/Estilos/Bibliotecas/jquery.ui.css?<%response.write(version)%>">
<!--<link rel="stylesheet" href="/wvdf_bib/BIB/Estilos/Bibliotecas/font-awesome.css?<%response.write(version)%>">-->
<!--<link rel="stylesheet" href="/wvdf_bib/BIB/Estilos/Bibliotecas/jquery.fullcalendar.css?<%response.write(version)%>"> -->
<link rel="stylesheet" href="/wvdf_bib/BIB/Estilos/Bibliotecas/fullcalendar.css?<%response.write(version)%>">
<link rel="stylesheet" href="/wvdf_bib/BIB/Estilos/Bibliotecas/jquery.datetimepicker.css?<%response.write(version)%>">
<link rel="stylesheet" href="/wvdf_bib/BIB/Estilos/Bibliotecas/jquery.bootstrap-duallistbox.css?<%response.write(version)%>">
<link rel="stylesheet" href="/wvdf_bib/BIB/Estilos/Bibliotecas/dialogs.css?<%response.write(version)%>">
<link rel="stylesheet" href="/wvdf_bib/BIB/Estilos/Bibliotecas/ng-table.min.css?<%response.write(version)%>">
<link rel="stylesheet" href="/wvdf_bib/BIB/Estilos/padroes.css?<%response.write(version)%>">
<link href="/wvdf_bib/BIB/Estilos/Bibliotecas/toaster.min.css?<%response.write(version)%>" rel="stylesheet" type="text/css">
<link href="/wvdf_bib/BIB/Estilos/Bibliotecas/smart-table.css?<%response.write(version)%>" rel="stylesheet">
<link href="/wvdf_bib/BIB/Estilos/Bibliotecas/diretivas.css?<%response.write(version)%>" rel="stylesheet">
<!--<link href="/wvdf_bib/BIB/Estilos/Bibliotecas/font-awesome-4.6.3/css/font-awesome.min.css?<%response.write(version)%>" rel="stylesheet" type="text/css"> -->
<link href="/wvdf_bib/BIB/Estilos/Bibliotecas/font-awesome-4.7.0/css/font-awesome.min.css?<%response.write(version)%>" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="/wvdf_bib/BIB/Estilos/Bibliotecas/ng-tags-input.min.css?<%response.write(version)%>">
<link rel="stylesheet" href="/wvdf_bib/BIB/Estilos/Bibliotecas/ng-tags-input.bootstrap.min.css?<%response.write(version)%>">
<!--<link rel="stylesheet" type="text/css" href="/wvdf_bib/BIB/Estilos/Bibliotecas/colReorder.bootstrap.min.css?<%response.write(version)%>">-->

<script src="/wvdf_bib/BIB/Scripts/funcAvisosUsuarios.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/funcFieldNumberCheck.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/funcSetCheckedStates.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/funcTextAreaLength.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/funcBotoesAcoes.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/funcReadFuncValue.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/funcRetiraAcento.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/funcGetVariavelURL.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/funcRedimensionarIframe.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/funcHtmlEntities.js?<%response.write(version)%>"></script>

<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/jquery.base.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/jquery.ui.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/jquery.fancybox.js?v=2.1.5"></script>
<script src="/wvdf_bib/BIB/Template/js/bootstrap.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Template/js/ace.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Template/js/ace-extra.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Template/js/ace-elements.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/jquery.alertify.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/jquery.maskedinput.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/jquery.moment.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/fullcalendar.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/locale/es.js?<%response.write(version)%>"></script>
<!--<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/jquery.fullcalendar.js?<%response.write(version)%>"></script> -->
<!--<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/jquery.fullcalendar.pt-br.js?<%response.write(version)%>"></script> -->
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/jquery.datetimepicker.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/jquery.fuelux.wizard.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/jquery.bootstrap-duallistbox.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/angular.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/angular-ui.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/angular-mask.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/angular-sanitize.js?<%response.write(version)%>"></script>

<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/ckeditor.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/jquery.iframeResizer.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/jquery.iframeResizer.contentWindow.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/FileSaver.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/bootstrap-tag.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/dialogs.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/angular.multiple-select.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/ng-table.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/toaster.min.js?<%response.write(version)%>" type="text/javascript"></script>
<script src="/wvdf_bib/BIB/Scripts/padroes.js?<%response.write(version)%>"></script>
 <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/smart-table.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/ui-select-infinity.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/diretivas.js?<%response.write(version)%>"></script>
 <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/ng-tags-input.min.js?<%response.write(version)%>"></script> 
 <script src="/wvdf_bib/BIB/Scripts/Bibliotecas/angular-datatables.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/angular-datatables.buttons.min.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/jquery.dataTables.min.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/bootstrap.min.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/dataTables.bootstrap.min.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/dataTables.buttons.min.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/buttons.bootstrap.min.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/jszip.min.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/pdfmake.min.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/vfs_fonts.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/buttons.colVis.min.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/buttons.flash.min.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/buttons.html5.min.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/buttons.print.min.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/dataTables.colReorder.min.js?<%response.write(version)%>"></script>
<script type="text/javascript" src="/wvdf_bib/BIB/Scripts/Bibliotecas/dataTables.colReorder.js"></script>

<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/locale/pt-br.js?<%response.write(version)%>"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular-i18n/1.2.15/angular-locale_pt-br.js"></script>
 <!--<script src="https://rawgit.com/Eonasdan/bootstrap-datetimepicker/master/src/js/bootstrap-datetimepicker.js"></script>-->
<!-- <script src="https://rawgit.com/atais/angular-eonasdan-datetimepicker/master/dist/angular-eonasdan-datetimepicker.js"></script>
 <link  rel="stylesheet" href="https://rawgit.com/Eonasdan/bootstrap-datetimepicker/master/build/css/bootstrap-datetimepicker.min.css"/> 
<link  rel="stylesheet" href="https://rawgit.com/Eonasdan/bootstrap-datetimepicker/master/build/css/bootstrap-datetimepicker-standalone.css"/>-->
<!--Bibliotecas de SOAP--> 
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/soapclient.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/angular.soap.js?<%response.write(version)%>"></script>

<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/ws-dominios.js?<%response.write(version)%>" type="text/javascript"></script>
<% if aPrograma <> "" then %>
<script src="/wvdf_bib/BIB/Scripts/Paginas/<%= aPrograma %>.js?<%response.write(version)%>"></script>
<% end if %>
		
<script src="/wvdf_bib/BIB/Scripts/funcPesquisaRelatorios.js?<%response.write(version)%>"></script>
<script src="/wvdf_bib/BIB/Scripts/funcConfiguraSwitchs.js?<%response.write(version)%>"></script>

<% if CheckFieldChange<>0 then %><script src="/wvdf_bib/BIB/Scripts/funcSetChangedStates-true.js?<%response.write(version)%>"></script>
<% else %><script src="/wvdf_bib/BIB/Scripts/funcSetChangedStates-false.js?<%response.write(version)%>"></script>
<% end if %>

<script src="/wvdf_bib/BIB/Scripts/Bibliotecas/fingerprint2.min.js"></script>
<script src="/wvdf_bib/BIB/Scripts/fhooks.js"></script>

<script type="text/javascript">
$(document).ready(function() {
/*
    if(!window.top.fhash){
        Fingerprint2.getLocalHash().then(function(hash){
        
            var paramsl = { 'aUsuarioSessao': getVariavelURL("aUsuarioSessao") };
            paramsl.fingerprint = hash;
            window.top.fhash = hash;
            $.getJSON('/WVDF_WS/ws_login.wso/acessoLogin/JSON?sJSON=' + JSON.stringify(paramsl)).then(function(data) {

                if (getVariavelURL("debug")) return;
            });
        });
    }
    else{
        var paramsl = { 'aUsuarioSessao': getVariavelURL("aUsuarioSessao") };

            paramsl.fingerprint = window.top.fhash;
            $.getJSON('/WVDF_WS/ws_login.wso/acessoLogin/JSON?sJSON=' + JSON.stringify(paramsl)).then(function(data) {

            });
    }
*/

});
</script>