<% If ((nVALUSR <> "0") And (nVALUSR <> "6") And (nVALUSR <> "9") ) Then %>
	<script>
			{
				var jnVALUSR= "<%=nVALUSR%>";
/*				
				if ( jnVALUSR == 1 ) {
					fSistemaUsuario_1();
					top.close();
					}
			    if ( jnVALUSR == 2 ) {
					fSistemaUsuario_2();
					top.close();
				}
			    if ( jnVALUSR == 3 ) {
					fSistemaUsuario_4();
					top.close();
				}
			    if ( jnVALUSR == 4 ) {
					fSistemaUsuario_5();
					top.close();
				}
			    if ( jnVALUSR == 5 ) {
					fSistemaUsuario_6();
					top.close();
				}
			    if ( jnVALUSR == -95 ) {
					fSistemaUsuario_95();
					top.close();
				}
			    if ( jnVALUSR == -98 ) {
					fSistemaUsuario_98();
					top.close();
				}
			    if ( jnVALUSR == -99 ) {
					fSistemaUsuario_99();
					top.close();
				}
			*/}
	</script>
<% nVALUSR=9 %>
<% End If %>