
	<script type="text/javascript" src="/wvdf_bib/scripts/third/jquery.positionBy.js"></script>

	<script type='text/javascript' src='/wvdf_bib/scripts/third/jquery.ajaxQueue.js'></script>
	<script type='text/javascript' src='/wvdf_bib/scripts/third/thickbox-compressed.js'></script>
	<script type='text/javascript' src='/wvdf_bib/scripts/third/jquery.autocomplete.js'></script>
	<script> $.fn.autocompleteAntigo = $.fn.autocomplete; </script>
	<link rel="stylesheet" type="text/css" href="/wvdf_bib/stylesheet/third/jquery.autocomplete.css" />
	<link rel="stylesheet" type="text/css" href="/wvdf_bib/stylesheet/third/thickbox.css" />