        <strong>&nbsp;Find&nbsp;</strong>
        <input type="submit" name="findfirst" value="&lt;&lt;" class="input-off" />
        <input type="submit" name="findprev"  value="&lt;"     class="input-off" />
        <input type="submit" name="find"      value="="        class="input-off" />
        <input type="submit" name="findnext"  value="&gt;"     class="input-off" />
        <input type="submit" name="findlast"  value="&gt;&gt;" class="input-off" />
