        <strong Class="Label">&nbsp;FIND&nbsp;</strong>
        <input type="submit" name="findfirst" value="&lt;&lt;" Class="btn btn-mini" />
        <input type="submit" name="findprev"  value="&lt;"     Class="btn btn-mini" />
        <input type="submit" name="find"      value="="        Class="btn btn-mini" />
        <input type="submit" name="findnext"  value="&gt;"     Class="btn btn-mini" />
        <input type="submit" name="findlast"  value="&gt;&gt;" Class="btn btn-mini" />
