<body topmargin="5" leftmargin="5" bgcolor="#E0E0E0" background="" bgproperties="fixed">

    <table border="0" class="ReportTable" Align="Center" Width="380px">
        <tr>
            <Td class="vermelho12" Align="Center">Voce nao possui <br> Direitos <br> Para acessar esta pagina!</td>
        </tr>
        <tr>
            <Td class="vermelho12" Align="Center"><br><br>Em caso de duvida contate seu supervisor!</td>
        </tr>
    </table>
</body>