    <meta http-equiv="cache-control"   content="no-cache" />
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" >
    <link type="text/css" rel="stylesheet" href="/wvdf_bib/stylesheet/stylesheet.css" />
	<link type="text/css"         href="/wvdf_bib/sistema/js/jquery-ui-1.10.0.custom/css/custom-theme/jquery-ui-1.10.0.custom.min.css" rel="stylesheet" />
	<script type="text/javascript" src="/wvdf_bib/sistema/js/jquery-ui-1.10.0.custom/js/jquery-1.9.0.js"></script> 
	<script type="text/javascript" src="/wvdf_bib/sistema/js/jquery-ui-1.10.0.custom/js/jquery-ui-1.10.0.custom.min.js"></script>   

	<!-- 
    <link type="text/css" rel="stylesheet" href="/wvdf_bib/stylesheet/third/jquery.ui/redmond/jquery-ui-1.8.15.custom.css" /> 
	<script type="text/javascript" src="/wvdf_bib/scripts/third/jquery.ui/jquery-ui-1.8.16.custom.min.js"></script>    
    <script type="text/javascript" src="/wvdf_bib/scripts/third/jquery.js"></script>	
	<script type="text/javascript" src="/wvdf_bib/scripts/third/jshotkeys/jquery.hotkeys.js"></script>
	<script type="text/javascript" src="/wvdf_bib/scripts/functions.js"></script>
    <script type="text/javascript" src="/wvdf_bib/scripts/init.js"></script>
	--> 
	
    <link href="/wvdf_bib/sistema/css/base.css" rel="stylesheet" type="text/css" />
    <link href="/wvdf_bib/sistema/css/docs.css" rel="stylesheet" type="text/css" />
    <link href="/wvdf_bib/sistema/css/prettify.css" rel="stylesheet" type="text/css" />
    <link href="/wvdf_bib/sistema/css/reset.css" rel="stylesheet" type="text/css" />
    <link href="/wvdf_bib/sistema/css/index.css" rel="stylesheet" type="text/css" />
    <link href="/wvdf_bib/sistema/css/bootstrap.css" rel="stylesheet" type="text/css" />