<script language="JavaScript">     
	function fBloqueio()
		{alert("ACESSO NEGADO, OBRIGADO !!!.");}
	function fIndisponivel()
		{alert("FUNCAO INDISPONIVEL NO MOMENTO");}
	function fAnterior()
		{alert("NOT FOUND");}
	function fProxima()
		{alert("NOT FOUND");}
	function fSistemaStatus()
		{alert("FUNCAO INATIVA NO SISTEMA NESTE MOMENTO, DEVIDO A ATUALIZACAO DOS DADOS. AGUARDE A LIBERACAO!!!");}
	function fSistemaUsuario_1()
		{alert("NAO EXISTE USUARIO COM TAIS ESPECIFICACOES, E-MAIL OU SENHA INVALIDOS, OBRIGADO !!!.");}
	function fSistemaUsuario_2()
		{alert("FUNCAO PERMITIDA SO AO ADMINISTRADOR, OBRIGADO !!!.");}
	function fSistemaUsuario_3()
		{alert("Sr(a). USUARIO VOCE JA ESTA LOGADO, OBRIGADO!!!");}
	function fSistemaUsuario_4()
		{alert("Sr(a). USUARIO SUA CONTA BLOQUEADA, CONTATE O ADMINISTRADOR DO SISTEMA, OBRIGADO!!!");}
	function fSistemaUsuario_5()
		{alert("Sr(a). USUARIO SUA CONTA ESTA EM USO, NECESSARIO DESBLOQUEIO OU LOGOUT, OBRIGADO!!!.");}
	function fSistemaUsuario_6()
		{alert("Sr(a). USUARIO SUA SENHA EXPIROU, CONTATE O ADMINISTRADOR DO SISTEMA, OU MODIFIQUE SUA SENHA OBRIGADO!!!.");}
	function fSistemaUsuario_7()
		{alert("FUNCAO INATIVA NO SISTEMA; NECESSARIO EXECUTAR O LOGIN PARA LIBERACAO, OBRIGADO!!!");}
	function fSistemaUsuario_94()
		{alert("ATENCAO !!!, SEU LOGIN OU SENHAS N+O CONFEREM VERIFIQUE E DIGITE NOVAMENTE ... OBRIGADO!!!");}
	function fSistemaUsuario_95()
		{alert("ATENCAO !!!, SUA CONTA ESTA FORA DO HORARIO DE ATIVIDADES ... OBRIGADO!!!");}
	function fSistemaUsuario_96()
		{alert("ATENCAO !!!, INCONSISTENCIA NA SUA CONEXAO (1) ... OBRIGADO!!!");}
	function fSistemaUsuario_97()
		{alert("ATENCAO !!!, INCONSISTENCIA NA SUA CONEXAO (2) ... OBRIGADO!!!");}
	function fSistemaUsuario_98()
		{alert("ATENCAO !!!, EXPIROU A VALIDADE DO SISTEMA... OBRIGADO!!!");}
	function fSistemaUsuario_99()
		{alert("ATENCAO !!!, ESTE TERMINAL NAO TEM AUTORIZACAO PARA ACESSAR O SISTEMA... OBRIGADO!!!");}
	function fMaximizar(){
		top.window.moveTo(0,0);
		if (document.all) {top.window.resizeTo(screen.availWidth,screen.availHeight);}
		else if (document.layers||document.getElementById) 
		{if (top.window.outerHeight<screen.availHeight||top.window.outerWidth<screen.availWidth)
		{top.window.outerHeight = screen.availHeight;top.window.outerWidth = screen.availWidth;}}
	}
</script>
